version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - BASE_URL=${BASE_URL}
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL}
      - OMNO_CLIENT_ID=${OMNO_CLIENT_ID}
      - OMNO_CLIENT_SECRET=${OMNO_CLIENT_SECRET}
  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http host.docker.internal:3000
    ports:
      - "4040:4040"