version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - BASE_URL=http://localhost
      - WEBHOOK_BASE_URL=https://<your-ngrok-id>.ngrok-free.app
      - OMNO_CLIENT_ID=your-client-id
      - OMNO_CLIENT_SECRET=your-client-secret
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN=
    command: http host.docker.internal:3000
    ports:
      - "4040:4040"
    depends_on:
      - app