version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - BASE_URL=http://localhost
      - WEBHOOK_BASE_URL= <Your webhook base url>
      - OMNO_CLIENT_ID= <Your client id>
      - OMNO_CLIENT_SECRET= <Your secret key>
      - HOST=0.0.0.0

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN= <Your ngrok auth token>
    command: http host.docker.internal:3000
    ports:
      - "4040:4040"